"""
Friday File Generator - Phase 5
Generate any type of file: documents, code, config, data, media.
"""
from __future__ import annotations

import os
import sys
import json
from typing import Optional, Dict, Any
from pathlib import Path

# ─── File Type Templates ──────────────────────────────────

CODE_TEMPLATES = {
    "python": """#!/usr/bin/env python3
\"\"\"{description}\"\"\"
from __future__ import annotations

def main():
    print("Hello from {filename}!")
    # TODO: Implement

if __name__ == "__main__":
    main()
""",
    "javascript": """/**
 * {description}
 */
function main() {{
    console.log("Hello from {filename}!");
    // TODO: Implement
}}

main();
""",
    "typescript": """/**
 * {description}
 */
function main(): void {{
    console.log("Hello from {filename}!");
    // TODO: Implement
}}

main();
""",
    "html": """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{description}</title>
    <style>
        body {{ font-family: sans-serif; margin: 2rem; }}
    </style>
</head>
<body>
    <h1>{description}</h1>
    <p>Generated by Friday File Generator</p>
</body>
</html>
""",
    "css": """/* {description} */
body {{
    margin: 0;
    padding: 1rem;
    font-family: sans-serif;
}}
""",
    "json": """{{
    "name": "{name}",
    "description": "{description}",
    "version": "1.0.0",
    "created_by": "Friday File Generator"
}}
""",
    "yaml": """# {description}
name: {name}
description: {description}
version: "1.0.0"
created_by: Friday File Generator
""",
    "xml": """<?xml version="1.0" encoding="UTF-8"?>
<root>
    <name>{name}</name>
    <description>{description}</description>
    <created_by>Friday File Generator</created_by>
</root>
""",
    "markdown": """# {name}

{description}

Generated by Friday File Generator.

## Features

- Feature 1
- Feature 2
- Feature 3

## Usage

```bash
# Example usage
```
""",
    "dockerfile": """FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

CMD ["python", "main.py"]
""",
    "shell": """#!/bin/bash
# {description}

set -e

echo "Running {name}..."

# TODO: Implement

echo "Done!"
""",
    "sql": """-- {description}

CREATE TABLE IF NOT EXISTS items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO items (name) VALUES ('example');
""",
    "go": """package main

import "fmt"

func main() {{
    fmt.Println("Hello from {filename}!")
    // TODO: Implement
}}
""",
    "rust": """fn main() {{
    println!("Hello from {filename}!");
    // TODO: Implement
}}
""",
    "java": """public class {name} {{
    public static void main(String[] args) {{
        System.out.println("Hello from {name}!");
        // TODO: Implement
    }}
}}
""",
}

DOCUMENT_TEMPLATES = {
    "requirements.txt": """# {description}
# Generated by Friday

requests>=2.31.0
""",
    "package.json": """{{
  "name": "{name}",
  "version": "1.0.0",
  "description": "{description}",
  "main": "index.js",
  "scripts": {{
    "start": "node index.js",
    "test": "echo \\"Error: no test specified\\" && exit 1"
  }},
  "keywords": [],
  "author": "Friday",
  "license": "MIT"
}}
""",
    "README.md": """# {name}

{description}

## Generated by Friday File Generator

### Installation

```bash
# Installation steps here
```

### Usage

```bash
# Usage examples here
```

### License

MIT
""",
}

# ─── File Generator ───────────────────────────────────────

def generate_file(
    path: str,
    file_type: str = "auto",
    description: str = "",
    content: str = "",
) -> str:
    """
    Generate a file of any type.
    If content is provided, writes it directly.
    If not, uses template based on file_type or extension.
    """
    try:
        # Ensure directory exists
        dir_path = os.path.dirname(path)
        if dir_path:
            os.makedirs(dir_path, exist_ok=True)
        
        # If content provided, write it directly
        if content:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            return f"[OK] File generated: {path} ({len(content)} bytes written)"
        
        # Determine file type
        if file_type == "auto":
            ext = Path(path).suffix.lower().lstrip(".")
            if ext in CODE_TEMPLATES:
                file_type = ext
            elif ext in ("md", "markdown"):
                file_type = "markdown"
            elif ext == "json":
                file_type = "json"
            elif ext == "yaml" or ext == "yml":
                file_type = "yaml"
            elif ext == "xml":
                file_type = "xml"
            elif ext == "txt":
                file_type = "text"
            else:
                file_type = "text"
        
        # Get template
        name = Path(path).stem
        filename = Path(path).name
        
        if not description:
            description = f"Generated file: {filename}"
        
        if file_type in CODE_TEMPLATES:
            template = CODE_TEMPLATES[file_type]
            content = template.format(
                name=name,
                filename=filename,
                description=description,
            )
        elif file_type in DOCUMENT_TEMPLATES:
            template = DOCUMENT_TEMPLATES[file_type]
            content = template.format(
                name=name,
                filename=filename,
                description=description,
            )
        else:
            # Plain text fallback
            content = f"# {description}\n\nGenerated by Friday File Generator.\n"
        
        # Write file
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        
        return f"[OK] File generated: {path}\nType: {file_type}\nSize: {len(content)} bytes"
    
    except Exception as e:
        return f"[FAIL] File generation error: {str(e)}"


def generate_from_llm(
    path: str,
    prompt: str,
    llm_provider: str = "gemini",
) -> str:
    """
    Generate file content using LLM, then write to path.
    Uses the available LLM to create appropriate content based on prompt.
    """
    try:
        # Try to use available LLM
        try:
            from friday.ai import ai_tool
            if ai_tool:
                llm_prompt = f"""Generate the complete content for a file at path: {path}

User request: {prompt}

Return ONLY the raw file content, no markdown code blocks, no explanations.
The content should be complete and ready to write directly to disk.
"""
                content = ai_tool("generate", prompt=llm_prompt)
                if content:
                    # Write the generated content
                    dir_path = os.path.dirname(path)
                    if dir_path:
                        os.makedirs(dir_path, exist_ok=True)
                    
                    with open(path, "w", encoding="utf-8") as f:
                        f.write(content)
                    
                    return f"[OK] LLM-generated file: {path}\nSize: {len(content)} bytes"
        except Exception as e:
            pass
        
        # Fallback: use template
        return generate_file(path, description=prompt)
    
    except Exception as e:
        return f"[FAIL] LLM file generation error: {str(e)}"


def batch_generate(files: list) -> str:
    """
    Generate multiple files at once.
    files: list of dicts with 'path', 'type', 'description', 'content' keys.
    """
    results = []
    for f in files:
        path = f.get("path", "output.txt")
        file_type = f.get("type", "auto")
        desc = f.get("description", "")
        content = f.get("content", "")
        
        result = generate_file(path, file_type, desc, content)
        results.append(result)
    
    return "\n\n".join(results)


def get_generator_status() -> str:
    """Get status of file generator."""
    lines = ["### FILE GENERATOR STATUS", ""]
    lines.append(f"[OK] Available code templates: {len(CODE_TEMPLATES)}")
    lines.append(f"[OK] Available document templates: {len(DOCUMENT_TEMPLATES)}")
    lines.append("")
    lines.append("**Supported types:**")
    for t in sorted(CODE_TEMPLATES.keys()):
        lines.append(f"  - {t}")
    return "\n".join(lines)


# ─── Integration with Friday Tools ───────────────────────────

def file_generator_tool(
    action: str = "generate",
    path: str = "",
    file_type: str = "auto",
    description: str = "",
    content: str = "",
    prompt: str = "",
) -> str:
    """
    Friday tool for file generation.
    Actions: generate, generate_llm, batch, status
    """
    if action == "status":
        return get_generator_status()
    
    if action == "generate":
        if not path:
            return "[FAIL] Path required for file generation."
        return generate_file(path, file_type, description, content)
    
    if action == "generate_llm":
        if not path or not prompt:
            return "[FAIL] Path and prompt required for LLM generation."
        return generate_from_llm(path, prompt)
    
    if action == "batch":
        try:
            files = json.loads(content) if content else []
            return batch_generate(files)
        except Exception as e:
            return f"[FAIL] Batch generation error: {e}"
    
    return f"Unknown action: {action}"


if __name__ == "__main__":
    print("Testing File Generator...\n")
    
    # Test status
    print("--- Generator Status ---")
    print(file_generator_tool("status"))
    
    # Test file generation
    print("\n--- Generate Python File ---")
    print(file_generator_tool(
        "generate",
        path="test_output/hello.py",
        file_type="python",
        description="A hello world script",
    ))
    
    # Test LLM generation (if available)
    # print(file_generator_tool(
    #     "generate_llm",
    #     path="test_output/api_server.py",
    #     prompt="Create a Flask API server with a GET /health endpoint",
    # ))
